### PR TITLE
Add automation to create components in DCI on each release

### PR DESCRIPTION
**Pull request by tonyskapunk**
On each release will generate [components](https://docs.distributed-ci.io/#component) in [distributed-ci](https://docs.distributed-ci.io/)

---
cc: @betoredhat, @ylamgarchal

### CODE REVIEW

**Review by betoredhat — APPROVED** [review]
Good stuff, LGTM

**Review by betoredhat — APPROVED** [review]
Lgtm

**Comment by tonyskapunk** [comment]
This one got merged a bit earlier than expected, I'll go ahead and remove it from `master` and re-submit the finalized branch

**Comment by tonyskapunk** [comment]
I've reverted the changes :sweat_smile: a new PR for this will be created

**Pull request merged**
